name: Deploy Staging

on:
  push:
    branches: [develop]

jobs:
  verify:
    name: Verify CI status
    runs-on: ubuntu-latest
    steps:
      - name: Confirm required checks
        run: |
          echo "Branch protection requires Lint, Unit Tests, and TestSprite QA to succeed before deployment."
          echo "This job runs after pushes to develop as a final gate."
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Placeholder deployment
        run: |
          echo "TODO: Invoke infra/ansible/deploy.yml when available."
          echo "Staging deployment pipeline will be implemented in a future phase."
