name: Sync labels

on:
  push:
    branches:
      - main
      - develop
      - qa/tests
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync labels
        uses: EndBug/label-sync@latest
        with:
          config-file: .github/labels.yml
